const palettes={
  trust:{name:'신뢰와 전문성',colors:['#12304A','#2C6A9B','#24A7AA','#EAF4F7']},
  bold:{name:'강한 인상',colors:['#121C2B','#E84A32','#FFB000','#FFF3D6']},
  calm:{name:'차분한 균형',colors:['#253D38','#5E8C76','#D8E9DE','#F6F7F3']},
  vivid:{name:'생동감',colors:['#492B7B','#E23C85','#F58D32','#FFF0E4']}
};
const recipes=[
 {id:'orbit',name:'오비트',tag:'전문적 · 확장성',styles:['professional','modern'],industries:['교육·컨설팅','기술·제조','전문 서비스'],layout:'horizontal',icon:'orbit'},
 {id:'bridge',name:'브리지',tag:'신뢰 · 연결',styles:['professional','friendly'],industries:['교육·컨설팅','전문 서비스'],layout:'horizontal',icon:'bridge'},
 {id:'frame',name:'프레임',tag:'정돈 · 명료함',styles:['minimal','professional'],industries:['교육·컨설팅','기술·제조','전문 서비스'],layout:'boxed',icon:'frame'},
 {id:'spark',name:'스파크',tag:'도전 · 변화',styles:['bold','modern'],industries:['교육·컨설팅','생활 서비스','기술·제조'],layout:'stacked',icon:'spark'},
 {id:'steps',name:'스텝스',tag:'성장 · 진전',styles:['professional','modern'],industries:['교육·컨설팅','전문 서비스'],layout:'horizontal',icon:'steps'},
 {id:'signal',name:'시그널',tag:'친근 · 즉시성',styles:['friendly','bold'],industries:['생활 서비스','교육·컨설팅'],layout:'stacked',icon:'signal'},
];
const defaults={brand:'브랜드 이름',slogan:'한 줄 설명',industry:'교육·컨설팅',style:'professional',palette:'trust',recipe:'bridge',view:'logo',cardFace:'front',scale:100,spacing:0,name:'홍길동',role:'대표',phone:'010-1234-5678',email:'hello@example.com',web:'www.example.com',locked:{symbol:false,type:false,color:false},started:false};
let state={...defaults,locked:{...defaults.locked}};
try{const saved=JSON.parse(localStorage.getItem('brand-recipe-v1')); if(saved) state={...state,...saved,locked:{...defaults.locked,...saved.locked}}}catch(e){}
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let setupStep=1, toastTimer;
function save(){localStorage.setItem('brand-recipe-v1',JSON.stringify(state));toast('저장했습니다')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function score(r){let s=0;s+=r.industries.includes(state.industry)?30:0;s+=r.styles.includes(state.style)?25:5;s+=r.layout==='horizontal'&&state.brand.length>6?20:12;s+=r.id===state.recipe?15:0;s+=({professional:['bridge','frame','steps'],minimal:['frame','orbit'],friendly:['bridge','signal'],bold:['spark','signal'],modern:['orbit','steps','spark']}[state.style]||[]).includes(r.id)?10:0;return s}
function sortedRecipes(){return [...recipes].sort((a,b)=>score(b)-score(a))}
function iconSvg(id,c1,c2){
 if(id==='orbit')return `<circle cx="45" cy="45" r="25" fill="none" stroke="${c1}" stroke-width="9"/><circle cx="69" cy="24" r="9" fill="${c2}"/>`;
 if(id==='bridge')return `<path d="M16 62 Q45 14 74 62" fill="none" stroke="${c1}" stroke-width="11" stroke-linecap="round"/><circle cx="45" cy="43" r="9" fill="${c2}"/>`;
 if(id==='frame')return `<rect x="16" y="16" width="58" height="58" rx="12" fill="none" stroke="${c1}" stroke-width="9"/><path d="M31 48h28" stroke="${c2}" stroke-width="9" stroke-linecap="round"/>`;
 if(id==='spark')return `<path d="M45 9l8 25 25 8-25 8-8 25-8-25-25-8 25-8z" fill="${c1}"/><circle cx="73" cy="17" r="7" fill="${c2}"/>`;
 if(id==='steps')return `<path d="M14 68h18V50h18V32h24" fill="none" stroke="${c1}" stroke-width="10" stroke-linejoin="round"/><path d="M65 21l14 11-14 11" fill="none" stroke="${c2}" stroke-width="7"/>`;
 return `<path d="M25 58c12 12 28 12 40 0" fill="none" stroke="${c1}" stroke-width="9" stroke-linecap="round"/><path d="M23 27l10 12M67 27L57 39M45 17v16" stroke="${c2}" stroke-width="7" stroke-linecap="round"/>`;
}
function logoSvg(recipeId=state.recipe,compact=false){const r=recipes.find(x=>x.id===recipeId)||recipes[0],p=palettes[state.palette],scale=state.scale/100,gap=36+state.spacing;const stacked=r.layout==='stacked';const font=state.style==='bold'?900:state.style==='minimal'?650:800;const brand=esc(state.brand||'브랜드 이름'),slogan=esc(state.slogan||'');const brandSize=Math.max(31,58-Math.max(0,state.brand.length-6)*4);return `<svg class="logo-svg" viewBox="0 0 620 240" xmlns="http://www.w3.org/2000/svg" aria-label="${brand} 로고"><g transform="translate(310 120) scale(${scale}) translate(-310 -120)">${stacked?`<g transform="translate(265 22)">${iconSvg(r.icon,p.colors[0],p.colors[2])}</g><text x="310" y="148" text-anchor="middle" font-family="Arial, sans-serif" font-size="${brandSize}" font-weight="${font}" fill="${p.colors[0]}">${brand}</text><text x="310" y="184" text-anchor="middle" font-family="Arial, sans-serif" font-size="19" letter-spacing="${2+state.spacing/8}" fill="${p.colors[1]}">${slogan}</text>`:`<g transform="translate(${88-gap/2} 70)">${iconSvg(r.icon,p.colors[0],p.colors[2])}</g><text x="${210+gap}" y="128" font-family="Arial, sans-serif" font-size="${brandSize}" font-weight="${font}" fill="${p.colors[0]}">${brand}</text><text x="${212+gap}" y="164" font-family="Arial, sans-serif" font-size="19" letter-spacing="${1+state.spacing/10}" fill="${p.colors[1]}">${slogan}</text>`}</g></svg>`}
function render(){const root=$('#app');root.innerHTML=`<main class="app">
 <header class="topbar"><div class="brand"><div class="brand-mark">R</div><div><strong>브랜드 레시피</strong><span>선택하고 직접 수정하세요</span></div></div><nav class="tabs" aria-label="제작물"><button data-view="logo" class="${state.view==='logo'?'active':''}">로고</button><button data-view="card" class="${state.view==='card'?'active':''}">명함</button></nav><div class="top-actions"><button class="btn ghost small hide-tablet" id="newProject">새 프로젝트</button><button class="btn primary small" id="save"><span class="save-label">프로젝트 </span>저장</button></div></header>
 <section class="workspace"><aside class="panel left"><div class="panel-head"><h2>추천 레시피</h2><p>선택한 조건을 기준으로 추천합니다. AI 호출은 없습니다.</p></div><div class="filters"><div class="filter-group"><span class="filter-label">인상</span><div class="chip-row">${[['professional','전문적'],['minimal','간결함'],['friendly','친근함'],['bold','강한 인상'],['modern','현대적']].map(x=>`<button class="chip ${state.style===x[0]?'active':''}" data-style="${x[0]}">${x[1]}</button>`).join('')}</div></div></div><button class="all-link" id="allRecipes">전체 레시피 보기 · ${recipes.length}개</button><div class="recipe-list">${sortedRecipes().map((r,i)=>`<button class="recipe ${state.recipe===r.id?'active':''}" data-recipe="${r.id}"><div class="recipe-preview">${r.icon==='spark'?'✦':r.icon==='bridge'?'⌒':r.icon==='steps'?'↗':'◇'}</div><div><strong>${r.name}</strong><small>${r.tag}<br>${i<3?`추천 ${score(r)}점`:'다른 선택지'}</small></div><span class="rank">${i<3?i+1:''}</span></button>`).join('')}</div></aside>
 <section class="panel center"><div class="canvas-tools"><div class="view-switch"><button data-view="logo" class="${state.view==='logo'?'active':''}">로고</button><button data-view="card" class="${state.view==='card'?'active':''}">명함</button></div><button class="btn icon small" id="undo" aria-label="기본값으로 되돌리기">↶</button><button class="btn small mobile-bar" id="openSettings">세부 수정</button><span class="canvas-meta">${state.view==='logo'?'가로형 로고':'90 × 50 mm 미리보기'}</span></div><div class="canvas-stage"><div class="artboard ${state.view==='logo'?'logo-mode':'card-mode'}">${state.view==='logo'?logoSvg():cardMarkup()}</div></div></section>
 <aside class="panel right" id="settings"><div class="panel-head settings-head"><div><h2>직접 수정</h2><p>선택한 값만 즉시 반영됩니다.</p></div><button class="btn icon small close-settings" id="closeSettings" aria-label="설정 닫기">×</button></div><div class="settings">${settingsMarkup()}</div><div class="final-ai"><strong>최종 마감에서만 AI 사용</strong><p>지금 결과를 먼저 완성한 뒤, 필요한 부분만 선택해 보완합니다.</p><button class="btn small" id="aiFinish">AI 마감 선택</button></div></aside></section>
 <nav class="mobile-bottom" aria-label="모바일 편집"><button id="mobileRecipes"><b>▦</b>레시피</button><button data-quick="color"><b>◉</b>색상</button><button data-quick="text"><b>T</b>문구</button><button id="mobileSettings"><b>☰</b>수정</button><button id="mobileExport"><b>⇩</b>저장</button></nav>
 </main>${state.started?'':setupMarkup()}`;bind();}
function cardMarkup(){const p=palettes[state.palette];return `<div class="card-face ${state.cardFace==='front'?'':'hidden'}"><div class="card-band" style="background:${p.colors[0]}"><div class="card-logo">${logoSvg()}</div></div><div class="card-info"><div class="card-name">${esc(state.name)}</div><div class="card-role">${esc(state.role)}</div><div class="contact-list">${esc(state.phone)}<br>${esc(state.email)}<br>${esc(state.web)}</div></div></div><div class="card-back ${state.cardFace==='back'?'':'hidden'}" style="background:${p.colors[0]}"><div class="card-logo">${logoSvg()}</div></div><div class="face-toggle"><button data-face="front" class="${state.cardFace==='front'?'active':''}">앞면</button><button data-face="back" class="${state.cardFace==='back'?'active':''}">뒷면</button></div>`}
function settingsMarkup(){const p=palettes[state.palette];return `<div class="section"><div class="section-title"><h3>브랜드 문구</h3><button class="lock ${state.locked.type?'on':''}" data-lock="type">${state.locked.type?'고정됨':'고정'}</button></div><div class="field"><label for="brandInput">브랜드 이름</label><input id="brandInput" value="${esc(state.brand)}" maxlength="24"></div><div class="field"><label for="sloganInput">설명 문구</label><input id="sloganInput" value="${esc(state.slogan)}" maxlength="36"></div></div><div class="section"><div class="section-title"><h3>색상 조합</h3><button class="lock ${state.locked.color?'on':''}" data-lock="color">${state.locked.color?'고정됨':'고정'}</button></div><div class="swatches">${Object.entries(palettes).map(([id,x])=>`<button class="swatch ${state.palette===id?'active':''}" data-palette="${id}" title="${x.name}" style="background:linear-gradient(135deg,${x.colors[0]} 0 48%,${x.colors[2]} 50%)"></button>`).join('')}</div></div><div class="section"><div class="section-title"><h3>배치와 크기</h3><button class="lock ${state.locked.symbol?'on':''}" data-lock="symbol">${state.locked.symbol?'고정됨':'고정'}</button></div><div class="field"><label>로고 크기</label><div class="range-row"><input id="scale" type="range" min="75" max="120" value="${state.scale}"><output>${state.scale}%</output></div></div><div class="field"><label>요소 간격</label><div class="range-row"><input id="spacing" type="range" min="-12" max="30" value="${state.spacing}"><output>${state.spacing}</output></div></div><div class="quick-actions"><button class="btn" data-action="simplify">단순하게</button><button class="btn" data-action="colorOnly">색상만 변경</button></div></div>${state.view==='card'?`<div class="section"><div class="section-title"><h3>명함 정보</h3></div>${[['name','이름'],['role','직함·학위'],['phone','전화'],['email','이메일'],['web','웹사이트']].map(([id,label])=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" value="${esc(state[id])}"></div>`).join('')}</div>`:''}<div class="section"><div class="section-title"><h3>내보내기</h3></div><div class="quick-actions"><button class="btn" id="downloadSvg">SVG</button><button class="btn" id="downloadPng">PNG</button><button class="btn" id="printPdf">PDF 인쇄</button><button class="btn" id="copyRecipe">레시피 저장</button></div></div>`}
function setupMarkup(){return `<div class="modal" role="dialog" aria-modal="true"><div class="modal-card"><div class="modal-top"><small>AI 호출 0회 · ${setupStep}/2</small><h1>${setupStep===1?'브랜드 기본 정보를 입력하세요':'원하는 인상을 고르세요'}</h1><p>${setupStep===1?'추천에 필요한 최소 정보입니다. 나중에 모두 수정할 수 있습니다.':'저장된 레시피를 조건에 맞게 정렬합니다.'}</p><div class="steps"><i class="on"></i><i class="${setupStep===2?'on':''}"></i></div></div><div class="modal-body">${setupStep===1?`<div class="form-grid"><div class="field"><label>브랜드 이름</label><input id="setupBrand" value="${esc(state.brand)}"></div><div class="field"><label>설명 문구</label><input id="setupSlogan" value="${esc(state.slogan)}"></div><div class="field"><label>업종</label><select id="setupIndustry">${['교육·컨설팅','전문 서비스','기술·제조','생활 서비스'].map(x=>`<option ${state.industry===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>우선 제작물</label><select><option>로고와 명함</option><option>로고만</option></select></div></div>`:`<div class="style-cards">${[['professional','전문적','신뢰와 안정이 먼저 보이게'],['minimal','간결함','장식을 줄이고 글자를 또렷하게'],['friendly','친근함','부드럽고 편안한 인상'],['bold','강한 인상','짧고 힘 있게 기억되도록'],['modern','현대적','선명한 구조와 변화감']].map(x=>`<button class="style-card ${state.style===x[0]?'active':''}" data-setup-style="${x[0]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div><div class="notice">추천을 사용하지 않고 전체 레시피를 직접 고를 수도 있습니다.</div>`}<div class="modal-actions"><button class="btn" id="setupBack" ${setupStep===1?'disabled':''}>이전</button><button class="btn primary" id="setupNext">${setupStep===2?'추천 결과 보기':'다음'}</button></div></div></div></div>`}
function bind(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});
 document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{state.style=b.dataset.style;if(!state.locked.symbol)state.recipe=sortedRecipes()[0].id;render()});
 document.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>{if(!state.locked.symbol)state.recipe=b.dataset.recipe;render()});
 document.querySelectorAll('[data-face]').forEach(b=>b.onclick=()=>{state.cardFace=b.dataset.face;render()});
 document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>{if(!state.locked.color){state.palette=b.dataset.palette;render()}else toast('색상 고정을 먼저 해제하세요')});
 document.querySelectorAll('[data-lock]').forEach(b=>b.onclick=()=>{state.locked[b.dataset.lock]=!state.locked[b.dataset.lock];render()});
 const map={brandInput:'brand',sloganInput:'slogan',name:'name',role:'role',phone:'phone',email:'email',web:'web'};Object.entries(map).forEach(([id,k])=>{const el=$('#'+id);if(el)el.oninput=e=>{state[k]=e.target.value;refreshCanvas()}});
 ['scale','spacing'].forEach(id=>{const el=$('#'+id);if(el)el.oninput=e=>{state[id]=+e.target.value;e.target.nextElementSibling.value=id==='scale'?state[id]+'%':state[id];refreshCanvas()}});
 $('#save').onclick=save; $('#undo').onclick=()=>{state={...defaults,started:true,locked:{...defaults.locked}};render();toast('처음 상태로 되돌렸습니다')};
 $('#newProject').onclick=()=>{state={...defaults,locked:{...defaults.locked}};setupStep=1;render()};
 $('#allRecipes').onclick=()=>{state.style='all';render();toast('전체 레시피를 표시합니다')};
 const open=()=>$('#settings').classList.toggle('open');['openSettings','mobileSettings'].forEach(id=>{const e=$('#'+id);if(e)e.onclick=open});$('#closeSettings').onclick=open;
 $('#mobileRecipes').onclick=openRecipeSheet;$('#mobileExport').onclick=()=>{state.view='logo';render();setTimeout(()=>$('#downloadPng')?.click(),30)};
 document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{open();setTimeout(()=>{const target=b.dataset.quick==='color'?$('.swatches'):$('#brandInput');target?.scrollIntoView({behavior:'smooth',block:'center'});target?.focus?.()},100)});
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='simplify'){state.style='minimal';state.recipe='frame';state.scale=94;state.spacing=4}else{const ids=Object.keys(palettes),i=(ids.indexOf(state.palette)+1)%ids.length;state.palette=ids[i]}render()});
 $('#downloadSvg').onclick=downloadSvg;$('#downloadPng').onclick=downloadPng;$('#printPdf').onclick=()=>window.print();$('#copyRecipe').onclick=()=>{save();toast('내 레시피로 저장했습니다')};
 $('#aiFinish').onclick=()=>toast('AI 마감은 기본 제작 기능 완성 후 연결합니다');
 const next=$('#setupNext');if(next)next.onclick=()=>{if(setupStep===1){state.brand=$('#setupBrand').value.trim()||'브랜드 이름';state.slogan=$('#setupSlogan').value.trim();state.industry=$('#setupIndustry').value;setupStep=2;render()}else{state.recipe=sortedRecipes()[0].id;state.started=true;save();render()}};
 const back=$('#setupBack');if(back)back.onclick=()=>{setupStep=1;render()};document.querySelectorAll('[data-setup-style]').forEach(b=>b.onclick=()=>{state.style=b.dataset.setupStyle;render()});
}
function openRecipeSheet(){const wrap=document.createElement('div');wrap.className='modal recipe-sheet';wrap.innerHTML=`<div class="modal-card"><div class="modal-top"><small>AI 호출 0회</small><h1>레시피를 직접 고르세요</h1><p>인상을 선택하면 추천 순서가 바로 바뀝니다.</p></div><div class="modal-body"><div class="chip-row sheet-styles">${[['professional','전문적'],['minimal','간결함'],['friendly','친근함'],['bold','강한 인상'],['modern','현대적']].map(x=>`<button class="chip ${state.style===x[0]?'active':''}" data-sheet-style="${x[0]}">${x[1]}</button>`).join('')}</div><div class="sheet-recipes">${sortedRecipes().map(r=>`<button class="recipe ${state.recipe===r.id?'active':''}" data-sheet-recipe="${r.id}"><div class="recipe-preview">${r.icon==='spark'?'✦':r.icon==='bridge'?'⌒':r.icon==='steps'?'↗':'◇'}</div><div><strong>${r.name}</strong><small>${r.tag}<br>추천 ${score(r)}점</small></div><span>›</span></button>`).join('')}</div><button class="btn dark sheet-close">선택 완료</button></div></div>`;document.body.appendChild(wrap);wrap.querySelector('.sheet-close').onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};wrap.querySelectorAll('[data-sheet-recipe]').forEach(b=>b.onclick=()=>{state.recipe=b.dataset.sheetRecipe;wrap.remove();render()});wrap.querySelectorAll('[data-sheet-style]').forEach(b=>b.onclick=()=>{state.style=b.dataset.sheetStyle;state.recipe=sortedRecipes()[0].id;wrap.remove();render();setTimeout(openRecipeSheet,0)})}
function refreshCanvas(){const art=$('.artboard');if(!art)return;art.innerHTML=state.view==='logo'?logoSvg():cardMarkup();document.querySelectorAll('[data-face]').forEach(b=>b.onclick=()=>{state.cardFace=b.dataset.face;render()})}
function download(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function downloadSvg(){const raw=logoSvg().replace('class="logo-svg"','width="1200" height="480"');download(`${state.brand}-logo.svg`,'image/svg+xml;charset=utf-8',raw);toast('SVG를 내려받았습니다')}
function downloadPng(){const raw=logoSvg().replace('class="logo-svg"','width="1200" height="480"');const img=new Image(),url=URL.createObjectURL(new Blob([raw],{type:'image/svg+xml'}));img.onload=()=>{const cv=document.createElement('canvas');cv.width=1200;cv.height=480;const ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);ctx.drawImage(img,0,0);cv.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.brand}-logo.png`;a.click();URL.revokeObjectURL(a.href);toast('PNG를 내려받았습니다')},'image/png');URL.revokeObjectURL(url)};img.src=url}
window.addEventListener('beforeunload',()=>localStorage.setItem('brand-recipe-v1',JSON.stringify(state)));render();
