const cardFronts=[
 ['classic','클래식 좌측','전문·기업'],['split','컬러 분할','신뢰·브랜드'],['topband','상단 띠','공공·교육'],['sideband','측면 띠','제조·기술'],['corner','코너 포인트','현대·정밀'],['center','중앙 미니멀','프리미엄'],['vertical','세로 리듬','크리에이티브'],['frame','프레임','법률·금융'],['diagonal','사선 분할','역동·성장'],['bottom','하단 블록','정보 중심'],['offset','비대칭','디자인·콘텐츠'],['monogram','모노그램','전문가·개인'],['capsule','캡슐 라벨','친근·서비스'],['grid','정보 그리드','기술·데이터'],['circle','원형 포인트','웰니스·라이프'],['outline','윤곽선','미니멀'],['editorial','편집형','문화·브랜드']
];
const cardBacks=[
 ['logo','중앙 로고'],['initial','대형 이니셜'],['slogan','슬로건 중심'],['vertical','세로 브랜드'],['dots','도트 패턴'],['lines','라인 패턴'],['split','양분 배경'],['stripe','포인트 띠'],['corner','코너 도형'],['frame','이중 프레임'],['solid','단색 역상'],['outline','선형 심볼'],['mono','모노그램'],['website','웹주소 중심'],['statement','브랜드 문장'],['symbol','심볼 확대'],['signature','서명형']
];
const cardRecipes=[];let cardSeq=1;cardFronts.forEach((f,fi)=>cardBacks.forEach((b,bi)=>cardRecipes.push({id:`c${cardSeq++}`,name:`${f[1]} × ${b[1]}`,tag:`${f[2]} · 양면`,front:f[0],back:b[0],fi,bi})));
function cardScore(c){let s=48;const key=state.style==='professional'?['classic','frame','grid','topband']:state.style==='minimal'?['center','outline','classic']:state.style==='friendly'?['capsule','circle','corner']:state.style==='bold'?['split','diagonal','vertical']:['offset','editorial','grid','corner'];if(key.includes(c.front))s+=24;if(profile().icons.includes(['shield','frame','pixel','bridge','spark','signal','leaf','orbit','pulse','steps'][c.fi%10]))s+=11;if(state.brand.length>9&&['classic','topband','bottom','grid'].includes(c.front))s+=9;s+=(16-c.bi)%7;return Math.min(99,s)}
function sortedCards(){return state.recommendMode?[...cardRecipes].sort((a,b)=>cardScore(b)-cardScore(a)||a.fi-b.fi):cardRecipes}
function cardTile(c,i){const p=palette(state.palette);return `<button class="recipe card-recipe ${state.cardRecipe===c.id?'active':''}" data-card-recipe="${c.id}"><div class="pair-thumb" style="--p:${p.colors[0]};--a:${p.colors[1]};--b:${p.colors[2]}"><i class="micro-card f-${c.front}"><b></b><em></em><span></span></i><i class="micro-card back b-${c.back}"><b></b><em></em></i></div><div><strong>${c.name}</strong><small>${c.tag}<br>${state.recommendMode?`추천 ${cardScore(c)}점`:`명함 ${c.id.slice(1)}`}</small></div><span class="rank">${state.recommendMode&&i<3?i+1:''}</span></button>`}
function cardReason(){const c=cardRecipes.find(x=>x.id===state.cardRecipe)||cardRecipes[0];return `${state.industry}에 맞는 ${c.name} 양면 구성입니다. 앞면과 뒷면을 함께 비교하세요.`}
function businessCardMarkup(){const c=cardRecipes.find(x=>x.id===state.cardRecipe)||cardRecipes[0],p=palette(state.palette),o=state.offsets,initials=esc((state.brand||'B').replace(/\s/g,'').slice(0,2));return `<div class="card-pair" style="--p:${p.colors[0]};--a:${p.colors[1]};--b:${p.colors[2]};--s:${p.colors[3]}"><section class="biz-card card-front f-${c.front}" aria-label="명함 앞면"><div class="bc-accent a1"></div><div class="bc-accent a2"></div><div class="bc-logo draggable" data-drag="cardLogo" style="transform:translate(${o.cardLogo.x}px,${o.cardLogo.y}px)">${logoSvg()}</div><div class="bc-info draggable" data-drag="cardInfo" style="transform:translate(${o.cardInfo.x}px,${o.cardInfo.y}px)"><strong>${esc(state.name)}</strong><small>${esc(state.role)}</small><p>${esc(state.phone)}<br>${esc(state.email)}<br>${esc(state.web)}</p></div><div class="bc-initial">${initials}</div>${guides()}</section><section class="biz-card card-back b-${c.back}" aria-label="명함 뒷면"><div class="bc-pattern"></div><div class="bc-back-logo">${logoSvg()}</div><div class="bc-back-initial">${initials}</div><strong class="bc-statement">${esc(state.slogan||'브랜드의 가치를 연결합니다')}</strong><span class="bc-web">${esc(state.web)}</span>${guides()}</section></div><div class="pair-labels"><span>앞면</span><span>뒷면</span></div>`}
