const PROJECTS_KEY='brand-recipe-projects-v1';
let historyStack=[],redoStack=[],historySuspended=false;
function projectList(){try{return JSON.parse(localStorage.getItem(PROJECTS_KEY))||[]}catch(e){return[]}}
function writeProjects(items){localStorage.setItem(PROJECTS_KEY,JSON.stringify(items))}
function cleanSnapshot(value=state){const x=structuredClone(value);delete x.screen;return x}
function trackHistory(){if(historySuspended){historySuspended=false;return}const snap=JSON.stringify(cleanSnapshot()),last=historyStack[historyStack.length-1];if(snap!==last){historyStack.push(snap);if(historyStack.length>60)historyStack.shift();redoStack=[]}updateHistoryButtons()}
function updateHistoryButtons(){const u=document.querySelector('#historyUndo'),r=document.querySelector('#historyRedo');if(u)u.disabled=historyStack.length<2;if(r)r.disabled=redoStack.length===0}
function undoHistory(){if(historyStack.length<2)return toast('되돌릴 이전 작업이 없습니다');redoStack.push(historyStack.pop());state={...state,...JSON.parse(historyStack[historyStack.length-1])};historySuspended=true;render();toast('이전 작업으로 돌아갔습니다')}
function redoHistory(){if(!redoStack.length)return toast('다시 적용할 작업이 없습니다');const snap=redoStack.pop();historyStack.push(snap);state={...state,...JSON.parse(snap)};historySuspended=true;render();toast('취소한 작업을 다시 적용했습니다')}
function saveProjectSnapshot(show=true){const items=projectList(),now=new Date().toISOString();if(!state.projectId)state.projectId='p-'+Date.now().toString(36);const entry={id:state.projectId,title:state.brand||'제목 없는 브랜드',updatedAt:now,view:state.view,palette:state.palette,recipe:state.recipe,cardRecipe:state.cardRecipe,snapshot:cleanSnapshot()};const i=items.findIndex(x=>x.id===entry.id);if(i>=0)items[i]=entry;else items.unshift(entry);writeProjects(items.slice(0,40));localStorage.setItem('brand-recipe-v2',JSON.stringify(state));if(show)toast('내 작업에 저장했습니다')}
function restoreProject(id){const item=projectList().find(x=>x.id===id);if(!item)return toast('저장한 작업을 찾을 수 없습니다');state={...defaults,...structuredClone(item.snapshot),projectId:item.id,offsets:{...defaults.offsets,...item.snapshot.offsets},locked:{...defaults.locked,...item.snapshot.locked},started:true};historyStack=[];redoStack=[];historySuspended=true;render();toast('저장한 작업을 불러왔습니다')}
function restoreLastSaved(){if(!state.projectId)return toast('먼저 프로젝트를 저장해 주세요');restoreProject(state.projectId)}
function duplicateProject(id){const item=projectList().find(x=>x.id===id);if(!item)return;state={...defaults,...structuredClone(item.snapshot),projectId:null,brand:(item.title||'브랜드')+' 복사본',started:true};saveProjectSnapshot(false);openHome();toast('복사본을 만들었습니다')}
function removeProject(id){const item=projectList().find(x=>x.id===id);if(!item||!confirm(`‘${item.title}’ 작업을 삭제할까요?`))return;writeProjects(projectList().filter(x=>x.id!==id));if(state.projectId===id)state.projectId=null;openHome();toast('저장 작업을 삭제했습니다')}
function newProjectFromHome(){state={...defaults,projectId:null,offsets:structuredClone(defaults.offsets),locked:{...defaults.locked}};step=1;historyStack=[];redoStack=[];render()}
function projectCardMarkup(item){const p=palette(item.palette),date=new Date(item.updatedAt).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});return `<article class="saved-card" style="--project-color:${p.colors[0]}"><button class="saved-preview" data-open-project="${item.id}"><span>${esc((item.title||'B').slice(0,2))}</span><small>${item.view==='card'?'양면 명함':'로고'}</small></button><div class="saved-meta"><strong>${esc(item.title)}</strong><small>${date} 저장</small><div><button data-open-project="${item.id}">열기</button><button data-copy-project="${item.id}">복제</button><button class="danger" data-delete-project="${item.id}">삭제</button></div></div></article>`}
function openHome(){save(false);const items=projectList(),app=document.querySelector('#app');app.innerHTML=`<main class="home-shell"><header class="home-top"><div class="brand"><div class="brand-mark">R</div><div><strong>잡앤킬 브랜드 레시피</strong><span>내 작업 홈</span></div></div><button class="btn primary" id="homeNew">새 디자인 만들기</button></header><section class="home-hero"><div><small>MY BRAND WORKSPACE</small><h1>저장한 로고와 명함을<br>언제든 다시 이어서 편집하세요.</h1><p>현재 베타는 이 브라우저에 안전하게 저장합니다. 회원 계정의 여러 기기 동기화는 서버 저장 단계에서 연결합니다.</p><div class="home-actions"><button class="btn primary" id="homeContinue">현재 작업 계속</button><button class="btn" id="homeNew2">새 프로젝트</button></div></div><div class="home-stat"><strong>${items.length}</strong><span>저장된 작업</span><b>로고 150 · 양면 명함 289</b></div></section><section class="saved-section"><div class="saved-head"><div><h2>내 작업</h2><p>최근 저장한 순서입니다.</p></div></div>${items.length?`<div class="saved-grid">${items.map(projectCardMarkup).join('')}</div>`:`<div class="saved-empty"><strong>아직 저장한 작업이 없습니다.</strong><p>디자인을 선택하고 상단의 ‘내 작업에 저장’을 누르면 여기에 나타납니다.</p><button class="btn primary" id="emptyNew">첫 디자인 만들기</button></div>`}</section></main>`;['homeNew','homeNew2','emptyNew'].forEach(id=>document.querySelector('#'+id)?.addEventListener('click',newProjectFromHome));document.querySelector('#homeContinue')?.addEventListener('click',()=>render());document.querySelectorAll('[data-open-project]').forEach(b=>b.onclick=()=>restoreProject(b.dataset.openProject));document.querySelectorAll('[data-copy-project]').forEach(b=>b.onclick=()=>duplicateProject(b.dataset.copyProject));document.querySelectorAll('[data-delete-project]').forEach(b=>b.onclick=()=>removeProject(b.dataset.deleteProject))}
function openProjects(){openHome()}
function injectProjectControls(){const actions=document.querySelector('.top-actions'),canvas=document.querySelector('.canvas-tools'),saved=projectList().length;if(actions&&!document.querySelector('#goHome')){actions.insertAdjacentHTML('afterbegin',`<button class="btn ghost small project-control" id="goHome">홈</button><button class="btn ghost small project-control" id="myProjects">내 작업 <span>${saved}</span></button>`);document.querySelector('#goHome').onclick=openHome;document.querySelector('#myProjects').onclick=openProjects;const saveButton=document.querySelector('#save');if(saveButton)saveButton.textContent='내 작업에 저장'}if(canvas&&!document.querySelector('#historyUndo')){const old=document.querySelector('#undo');if(old){old.id='resetPositionsTop';old.textContent='초기 배치';old.setAttribute('aria-label','현재 디자인의 배치를 처음 상태로 되돌리기');old.classList.remove('icon')}canvas.insertAdjacentHTML('afterbegin','<div class="history-tools" aria-label="편집 기록"><button class="btn icon small" id="historyUndo" aria-label="실행취소" title="아까 한 작업으로 돌아가기">↶</button><button class="btn icon small" id="historyRedo" aria-label="다시실행" title="취소한 작업 다시 적용">↷</button><button class="btn small restore-label" id="restoreSaved">마지막 저장본 복원</button></div>');document.querySelector('#historyUndo').onclick=undoHistory;document.querySelector('#historyRedo').onclick=redoHistory;document.querySelector('#restoreSaved').onclick=restoreLastSaved;const reset=()=>{state.offsets=structuredClone(defaults.offsets);render();toast('현재 배치를 처음 상태로 돌렸습니다')};document.querySelector('#resetPositionsTop').onclick=reset}updateHistoryButtons()}
function injectMobileHome(){const nav=document.querySelector('.mobile-bottom');if(nav&&!document.querySelector('#mobileHome')){nav.insertAdjacentHTML('afterbegin','<button id="mobileHome"><b>⌂</b>홈</button>');document.querySelector('#mobileHome').onclick=openHome}}
const baseStudioRender=render;
render=function(){baseStudioRender();injectProjectControls();injectMobileHome();trackHistory()};
const baseStudioRefresh=refresh;
refresh=function(){baseStudioRefresh();trackHistory()};
injectProjectControls();injectMobileHome();trackHistory();
