const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');

(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const url=process.env.STUDIO_URL||'http://127.0.0.1:4173';
 const assert=(ok,message)=>{if(!ok)throw new Error(message)};
 await page.goto(url,{waitUntil:'networkidle'});
 await page.evaluate(()=>localStorage.clear());
 await page.reload({waitUntil:'networkidle'});
 await page.fill('#setupBrand','잡앤킬 랩');
 await page.selectOption('#setupIndustry',{label:'정보통신업'});
 await page.click('#setupNext');
 await page.click('[data-setup-style="modern"]');
 await page.click('#setupNext');
 await page.waitForSelector('#studioIndustry');
 const initial=await page.locator('.artboard').innerHTML();
 const initialRecipe=await page.locator('.recipe.active').getAttribute('data-recipe');
 await page.selectOption('#studioIndustry',{label:'보건·사회복지'});
 const industryChanged=await page.locator('.artboard').innerHTML();
 const industryRecipe=await page.locator('.recipe.active').getAttribute('data-recipe');
 assert(initial!==industryChanged&&initialRecipe!==industryRecipe,'업종 변경이 작업판과 선택 레시피를 바꾸지 않음');
 await page.click('[data-style="friendly"]');
 const friendly=await page.locator('.artboard').innerHTML();
 assert(industryChanged!==friendly,'인상 변경이 작업판을 바꾸지 않음');
 assert(await page.locator('.logo-svg.style-friendly').count()>0,'친근함 스타일 클래스가 작업판에 반영되지 않음');
 const firstSix=await page.locator('.logo-recipe').evaluateAll(items=>items.slice(0,6).map(x=>x.querySelector('strong').textContent));
 assert(new Set(firstSix).size===6,'상위 6개 로고가 서로 다른 방향으로 보이지 않음');
 assert(await page.getByText(/추천 \d+점/).count()===0,'근거 없는 추천 점수가 남아 있음');
 await page.click('[data-mode="all"]');
 await page.locator('.logo-recipe').nth(9).click();
 const directRecipe=await page.locator('.recipe.active').getAttribute('data-recipe');
 await page.click('[data-style="bold"]');
 assert(await page.locator('.recipe.active').getAttribute('data-recipe')===directRecipe,'직접 선택한 레시피를 인상 변경이 덮어씀');
 await page.click('[data-view="card"]');
 assert(await page.locator('.biz-card').count()===2,'명함 앞면·뒷면이 함께 표시되지 않음');
 const guidesBefore=await page.locator('.biz-card .safe-line').count();
 await page.click('#guideToggle');
 assert(guidesBefore===2&&await page.locator('.biz-card .safe-line').count()===0,'인쇄 가이드 토글 실패');
 await page.click('#save');
 await page.click('#goHome');
 assert(await page.locator('.saved-card').count()===1,'저장 작업이 홈에 나타나지 않음');
 await page.locator('.saved-card [data-open-project]').first().click();
 assert(await page.locator('#historyUndo').count()===1&&await page.locator('#historyRedo').count()===1,'실행취소/다시실행 도구 없음');
 fs.mkdirSync(path.join(__dirname,'output'),{recursive:true});
 await page.screenshot({path:path.join(__dirname,'output','desktop-qa.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.reload({waitUntil:'networkidle'});
 assert(await page.locator('.mobile-bottom').isVisible(),'모바일 하단 도구가 표시되지 않음');
 await page.screenshot({path:path.join(__dirname,'output','mobile-qa.png'),fullPage:true});
 await browser.close();
 console.log('PASS desktop interaction: industry/style changes, direct selection, double-sided card, guides, saved work');
 console.log('PASS responsive render: 1440px and 390px');
})().catch(error=>{console.error(error);process.exit(1)});
